name: flutter_2fa
description: Flutter 2FA
publish_to: "none"
version: 1.0.0+1

environment:
  # caret syntax fixes a lot of warnings
  # https://github.com/dart-lang/sdk/issues/52672
  sdk: "^3.1.4"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: "2.2.0"
  isar: "4.0.0-dev.14"
  isar_flutter_libs: "4.0.0-dev.14"
  flutter_riverpod: "2.3.6"
  riverpod_annotation: "2.1.1"

  cupertino_icons: "1.0.2"
  remixicon: ^1.0.0
  path_provider: "2.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: "2.0.0"
  custom_lint: "0.4.0"
  very_good_analysis: "5.1.0"
  riverpod_lint: "1.3.2"

  freezed: "2.3.5"
  build_runner: "2.4.6"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/geist-mono/GeistMono-Black.otf
          weight: 900
        - asset: assets/fonts/geist-mono/GeistMono-Bold.otf
          weight: 700
        - asset: assets/fonts/geist-mono/GeistMono-Regular.otf
          weight: 400
        - asset: assets/fonts/geist-mono/GeistMono-UltraLight.otf
          weight: 200
        - asset: assets/fonts/geist-mono/GeistMono-Thin.otf
          weight: 100
