name: flutter_2fa
description: Flutter 2FA
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: "1.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: "2.0.0"
  very_good_analysis: "5.1.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/geist-mono/GeistMono-Black.otf
          weight: 900
        - asset: assets/fonts/geist-mono/GeistMono-Bold.otf
          weight: 700
        - asset: assets/fonts/geist-mono/GeistMono-Regular.otf
          weight: 400
        - asset: assets/fonts/geist-mono/GeistMono-UltraLight.otf
          weight: 200
        - asset: assets/fonts/geist-mono/GeistMono-Thin.otf
          weight: 100
